# Generated by Django 2.1.3 on 2018-12-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField(default='0', null=True)),
                ('answer', models.CharField(default='venkatesh', max_length=200)),
                ('a', models.CharField(default='dhd', max_length=200)),
                ('aub_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='venkatesh', max_length=200)),
                ('course_id', models.IntegerField(default='0')),
                ('course_faculty', models.CharField(default='venkatesh', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(default='venkatesh', max_length=200)),
                ('faculty_email', models.EmailField(default='venkatesh', max_length=200)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='venkatesh', max_length=25)),
                ('password', models.CharField(default='venkatesh', max_length=25)),
                ('email', models.EmailField(default='venkatesh2', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('q', models.CharField(default='ass', max_length=200)),
                ('question_text', models.CharField(max_length=200)),
                ('question_course', models.CharField(default='dfasdfksaof', max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_review', models.IntegerField(default='0')),
                ('answer_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_name', models.CharField(default='', max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='m', max_length=1)),
                ('current_year', models.CharField(default='', max_length=3)),
                ('student_email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Question'),
        ),
    ]
